[package]
name = "server"
version = "0.1.0"
authors = ["David DiMaria <david.dimaria@littlebearlabs.io>"]
edition = "2018"

[dependencies]
libwebrtc = { path = "../webrtc", package="webrtc" }
nanoid = "0.4.0"
prost = "0.8"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tonic = "0.5"
tracing = "0.1"
tracing-subscriber = { version = "0.2.19", features = ["fmt", "env-filter"] }

[build-dependencies]
tonic-build = "0.5"
